name: Sync To Gitee for ani2xcur

#on: [ push, delete, create ]
on: 
  schedule:
  # * is a special character in YAML so you have to quote this string
  # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
  - cron: '0 8 1/7 * *'
  #push:
  #delete:
  #create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:licyk/ani2xcur.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:four-dishes/ani2xcur.git