name: Build SD Portable Download Page

on: 
  schedule:
  - cron: '10 22 * * *'
  # push:
  # delete:
  # create:
  workflow_dispatch:

jobs:
  Build-SD-Portable-Download-Page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: List files in the repository
        run: |
          cd "${{ github.workspace }}"
          ls "${{ github.workspace }}"

      - name: Install SD WebUI All In One
        shell: bash
        run: |
          python -m venv "${{ github.workspace }}/.venv"
          "${{ github.workspace }}/.venv/bin/python" -m pip install --upgrade pip
          "${{ github.workspace }}/.venv/bin/python" -m pip install "sd-webui-all-in-one[models]"

      - name: Build SD Portable Download Page
        shell: bash
        run: |
          "${{ github.workspace }}/.venv/bin/python" -m sd_webui_all_in_one self-manager portable list \
            --output "${{ github.workspace }}/artifact/portable_list.json" \
            --hf-repo-id "licyk/sdnote" \
            --hf-repo-type "model" \
            --ms-repo-id "licyks/sdnote" \
            --ms-repo-type "model"

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: page_file
          path: ${{ github.workspace }}/artifact/

      - name: Configure Git
        env:
          DEPLOY_PRI: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          GIT_USERNAME: ${{ github.repository_owner }}
          GIT_EMAIL: ${{ github.repository_owner }}@user.github.com
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "$GIT_USERNAME"
          git config --global user.email "$GIT_EMAIL"

      - name: Commit Repo
        env:
          GIT_URL: 'git@github.com:licyk/resources.git'
        run: |
          git clone "$GIT_URL" "${{ github.workspace }}/repo"
          git -C "${{ github.workspace }}/repo" checkout gh-pages
          cp -rf "${{ github.workspace }}/artifact/"* "${{ github.workspace }}/repo/"
          git -C "${{ github.workspace }}/repo" add -A || true
          git -C "${{ github.workspace }}/repo" commit -m "Build SD Portable Download Page. Time: $(date +'%Y-%m-%d %H:%M:%S')" || true

      - name: Push Repo
        run: |
          git -C "${{ github.workspace }}/repo" push origin HEAD:gh-pages || true
