name: Clean HuggingFace Repo Space

on:
    workflow_dispatch:
        inputs:
            hf_repo_id:
                description: HuggingFace 仓库 ID
                required: true
                type: string
            hf_repo_type:
                description: HuggingFace 仓库类型
                required: false
                type: string
            hf_repo_branch:
                description: HuggingFace 仓库分支
                required: false
                type: string
    schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    # https://docs.github.com/zh/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    - cron: '0 15 * * 0'

jobs:
    Clean-HF-Repo-Space:
        runs-on: ubuntu-latest
        steps:
            - name: Config HuggingFace Python Library
              shell: bash
              run: |
                pip install "huggingface_hub[cli]" --break-system-package

            - name: Clean HuggingFace Repo Space
              shell: python
              env:
                HF_TOKEN: ${{ secrets.HF_TOKEN }}
                HF_REPO_ID: ${{ inputs.hf_repo_id }}
                HF_REPO_TYPE: ${{ inputs.hf_repo_type }}
                HF_REPO_BRANCH: ${{ inputs.hf_repo_branch }}
              run: |
                import os
                from huggingface_hub import super_squash_history

                super_squash_history(
                    repo_id=os.getenv("HF_REPO_ID", "licyk/sdnote"),
                    repo_type=os.getenv("HF_REPO_TYPE") or None,
                    branch=os.getenv("HF_REPO_BRANCH") or None,
                    token=os.getenv("HF_TOKEN") or None,
                )
