name: Clean Outdated SD Portable

on:
  schedule:
  - cron: '30 15 * * *'
  # push:
  # delete:
  # create:
  workflow_dispatch:

jobs:
  Clean-Outdated-SD-Portable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Setup uv
        uses: astral-sh/setup-uv@v8

      - name: Config HuggingFace / ModelScope Python Library
        shell: bash
        env:
          UV_SYSTEM_PYTHON: 1
        run: |
          uv pip install huggingface_hub modelscope

      - name: List files in the repository
        run: |
          cd "${{ github.workspace }}"
          ls "${{ github.workspace }}"

      - name: Clean Outdated SD Portable
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MODELSCOPE_API_TOKEN: ${{ secrets.MODELSCOPE_API_TOKEN }}
          HF_REPO_ID: licyk/sd-webui-all-in-one
          HF_REPO_TYPE: model
          MS_REPO_ID: licyks/sd-webui-all-in-one
          MS_REPO_TYPE: model
          DAY_THRESHOLD: 30
        run: |
          python "${{ github.workspace }}/scripts/clean_outdated_sd_portable.py"
