name: Clean Outdated SD Portable

on:
  schedule:
  - cron: '30 15 * * *'
  # push:
  # delete:
  # create:
  workflow_dispatch:

jobs:
  Clean-Outdated-SD-Portable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          cd "${{ github.workspace }}"
          ls "${{ github.workspace }}"

      - name: Config HuggingFace / ModelScope Python Library
        shell: bash
        run: |
          pip install huggingface_hub modelscope --break-system-package

      - name: Clean Outdated SD Portable
        shell: bash
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MODELSCOPE_API_TOKEN: ${{ secrets.MODELSCOPE_API_TOKEN }}
          HF_REPO_ID: licyk/sdnote
          HF_REPO_TYPE: model
          MS_REPO_ID: licyks/sdnote
          MS_REPO_TYPE: model
          DAY_THRESHOLD: 60
        run: |
          python "${{ github.workspace }}/scripts/clean_outdated_sd_portable.py"
