name: Sync To Gitee

on: 
  schedule:
    - cron: '0 16 * * *' # 北京时间每日 00:00 执行
  workflow_dispatch:

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    strategy:
      # 即使其中一个同步失败, 也继续执行其他的同步任务
      fail-fast: false
      matrix:
        # 在这里统一定义需要同步的仓库名
        # 格式为: "GitHub 仓库名:Gitee 仓库名"
        repo: [
          "blog:blog",
          "term-sd:term-sd",
          "scrcpy-tui:scrcpy-tui",
          "ani2xcur:ani2xcur",
          "bili-dl-merge:bili-dl-merge",
          "README-collection:README-collection",
          "private-code:private-code",
          "hub-action:hub-action",
          "t:tt",
          "advanced_euler_sampler_extension:advanced_euler_sampler_extension",
          "sd-webui-all-in-one:sd-webui-all-in-one",
          "sd-webui-tcd-sampler:sd-webui-tcd-sampler",
          "ComfyUI-TCD-Sampler:ComfyUI-TCD-Sampler",
          "ComfyUI-Restart-Sampler:ComfyUI-Restart-Sampler"
        ]

    steps:
      - name: Parse repo names
        id: info
        run: |
          # 将 "A:B" 拆分为两个变量
          SRC=$(echo "${{ matrix.repo }}" | cut -d':' -f1)
          DEST=$(echo "${{ matrix.repo }}" | cut -d':' -f2)
          echo "src=$SRC" >> $GITHUB_OUTPUT
          echo "dest=$DEST" >> $GITHUB_OUTPUT

      - name: Sync ${{ steps.info.outputs.src }} to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:licyk/${{ steps.info.outputs.src }}.git"
          destination-repo: "git@gitee.com:licyk/${{ steps.info.outputs.dest }}.git"