name: Sync To Gitlab

on: 
    schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 16 * * *' # 每日24点进行同步
    # push:
    # delete:
    # create:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Sync blog to Gitlab
              uses: wearerequired/git-mirror-action@master
              env:
                  # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }} # 将私钥读取到github action环境变量中
              with:
                  # 注意替换为你的 GitHub 源仓库地址
                  source-repo: git@github.com:licyk/blog.git
                  # 注意替换为你的 Gitlab 目标仓库地址
                  destination-repo: git@gitlab.com:licyk/blog.git

            - name: Sync term-sd to Gitlab
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:licyk/term-sd.git
                  destination-repo: git@gitlab.com:licyk/term-sd.git

            - name: Sync scrcpy-tui to Gitlab
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:licyk/scrcpy-tui.git
                  destination-repo: git@gitlab.com:licyk/scrcpy-tui.git
      
            - name: Sync ani2xcur to Gitlab
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:licyk/ani2xcur.git
                  destination-repo: git@gitlab.com:licyk/ani2xcur.git

            - name: Sync bili-dl-merge to Gitlab
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:licyk/bili-dl-merge.git
                  destination-repo: git@gitlab.com:licyk/bili-dl-merge.git

            - name: Sync README-collection to Gitlab
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:licyk/README-collection.git
                  destination-repo: git@gitlab.com:licyk/README-collection.git

            - name: Sync private-code to Gitlab
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:licyk/private-code.git
                  destination-repo: git@gitlab.com:licyk/private-code.git

            - name: Sync hub-action to Gitlab
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:licyk/hub-action.git
                  destination-repo: git@gitlab.com:licyk/hub-action.git

            - name: Sync t to Gitlab
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:licyk/t.git
                  destination-repo: git@gitlab.com:licyk/t.git