name: Sync To Gitlab

on: 
    schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 16 * * *' # 每日24点进行同步
    # push:
    # delete:
    # create:
    workflow_dispatch:

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    strategy:
      # 即使其中一个同步失败, 也继续执行其他的同步任务
      fail-fast: false
      matrix:
        # 在这里统一定义需要同步的仓库名
        # 格式:
        # 1. 原仓库和目的仓库名字不同时: "原仓库名:目的仓库名"
        # 2. 原仓库和目的仓库名字不同时: "仓库名"
        repo: [
          "term-sd",
          "t",
          "hub-action",
          "cursors-archive",
          "psh2bat",
          "ani2xcur-cli",
          "repo_mirror_tools",
          "ani2xcur",
          "sd-webui-all-in-one",
          "SDNote",
          "stablediffusion",
          "README-collection",
          "a1111-sd-webui-haku-img",
          "ssfconv",
          "sd-webui-wd14-tagger",
          "invoke_wd14_tagger",
          "ComfyUI-HakuImg",
          "sd-webui-licyk-style-image",
          "sd_forge_hypertile_svd_z123",
          "ComfyUI-TCD-Sampler",
          "action-gitee-release",
          "invoke_tipo",
          "licyk",
          "ComfyUI-Restart-Sampler",
          "PBRemTools",
          "advanced_euler_sampler_extension",
          "sd-webui-tcd-sampler",
          "scrcpy-tui",
          "cinnamon-theme-transparent",
          "bili-dl-merge",
          "qwen-tts-webui"
        ]

    steps:
      - name: Parse repo names
        id: info
        run: |
          if echo "${{ matrix.repo }}" | grep -q ":"; then
              # 将 "A:B" 拆分为两个变量
              SRC=$(echo "${{ matrix.repo }}" | cut -d':' -f1)
              DEST=$(echo "${{ matrix.repo }}" | cut -d':' -f2)
          else
              SRC="${{ matrix.repo }}"
              DEST="${{ matrix.repo }}"
          fi
          echo "src=${SRC}" >> "${GITHUB_OUTPUT}"
          echo "dest=${DEST}" >> "${GITHUB_OUTPUT}"

      - name: Sync ${{ steps.info.outputs.src }} to Gitee
        continue-on-error: true
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:licyk/${{ steps.info.outputs.src }}.git"
          destination-repo: "git@gitlab.com:licyk/${{ steps.info.outputs.dest }}.git"

